version: "3.8"

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./log:/var/log

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/app/public:cached

  # .envファイルの「DB_HOST」とサービス名を合わせる
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # .envファイルの「DB_DATABASE」とMYSQL_DATABASEを合わせる
      MYSQL_DATABASE: sample_db
      TZ: "Asia/Tokyo"
      # 文字コード指定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin-dl:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 8580:80
    volumes:
      - /sessions

  mailcatcher-dl:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
